---
# tasks file for roles/httpd
- name: ensure desired state of httpd
  yum:
    name: httpd
    state: "{{ httpd_state }}"

- name: httpd service state
  service:
    name: httpd
    enabled: "{{httpd_service_enabled}}"
    state: "{{httpd_service_state}}"
  register: register_var

- name: httpd state
  debug:
    msg: "{{register_var.state}}"